title = "Rajat Khanna"
baseURL = "http://legalimpurity.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Rajat Khanna"
    author = "Rajat Khanna"
    description = "Mobile developer based in New Delhi, India."
    logoBig = "/images/logo/rk-logo-450.png"
    logoSmall = "/images/logo/rk-logo-150.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "legalimpurity"
    linkedin = "rajatkhanna08"
    github = "legalimpurity"
    email = "legalimpurity@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
